#!/bin/bash

# Update Linux Mint
sudo apt update
sudo apt upgrade -y

# Install Ansible
if ! [ -x "$(command -v ansible)" ]; then
  sudo apt install ansible -y
fi

# Install Open SSH Server
apt install openssh-server -y

# Install Git
apt install git -y